# Generated by Django 5.0.3 on 2024-04-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customers_store_custo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customers',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
